GET http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome":"Igor",
    "ativo":"true"
}

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome":"Carlos2",
    "ativo":"true"
}