GET http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "usuario":"Igor",
    "ativo":"true"
}

###

GET http://localhost:3000/usuarios/2

###

DELETE http://localhost:3000/usuarios/1
